name: Makefile CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Run distcheck
      run: PROJECT=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC make image
